/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShapshotsPanel.java
 *
 * Created on 19.03.2011, 9:38:37
 */

package ru.kc.module.snapshots.ui;

/**
 *
 * @author chapaj
 */
public class SnapshotsPanel extends javax.swing.JPanel {

    /** Creates new form ShapshotsPanel */
    public SnapshotsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        addFolder = new javax.swing.JButton();
        addSnapshot = new javax.swing.JButton();
        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        addFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/kc/module/snapshots/img/folder.png"))); // NOI18N
        addFolder.setToolTipText("Create folder");
        addFolder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(addFolder);

        addSnapshot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/kc/module/snapshots/img/foto.png"))); // NOI18N
        addSnapshot.setToolTipText("Create snapshots");
        addSnapshot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addSnapshot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(addSnapshot);

        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/kc/module/snapshots/img/up.png"))); // NOI18N
        up.setToolTipText("Move up");
        up.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        up.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jToolBar1.add(up);

        down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/kc/module/snapshots/img/down.png"))); // NOI18N
        down.setToolTipText("Move down");
        down.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        down.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(down);

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/kc/module/snapshots/img/delete.png"))); // NOI18N
        remove.setToolTipText("Delete");
        remove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        remove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(remove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addFolder;
    public javax.swing.JButton addSnapshot;
    public javax.swing.JButton down;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JToolBar jToolBar1;
    public javax.swing.JButton remove;
    public javax.swing.JTree tree;
    public javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables

}
